CowBook/routes.py
from datetime import datetime

from flask import render_template, request, redirect, url_for, flash, Blueprint
from flask_security import login_required, current_user
from sqlalchemy.exc import IntegrityError

from CowBook.Forms.NoteForm import NoteForm
from CowBook.Forms.BredForm import BredForm
from CowBook.Forms.Cow.EditParentForm import EditParentForm
from CowBook.Forms.DeathForm import DeathForm
from CowBook.Forms.EditTreatmentForm import EditTreatmentForm
from CowBook.Forms.EventForm import EventForm
from CowBook.Forms.PregnancyCheckForm import PregnancyCheckForm
from CowBook.Forms.SaleForm import SaleForm
from CowBook.Forms.TreatmentForm import TreatmentForm
from CowBook.Forms.WeightForm import WeightForm
from CowBook.Models.Cow.CowModel import get_by_id, get_calves, get_all, get_active, get_inactive
from CowBook.Forms.Cow.CowForm import CowForm
from CowBook.Models.Cow.CowTable import CowTable
from CowBook.Forms.Cow.EditCowForm import EditCowForm
from CowBook.Models.Death import get_dead
from CowBook.Models.DeathTable import DeathTable
from CowBook.Models.Note import NoteTable
from CowBook.Models.Sale import get_sold
from CowBook.Models.SoldTable import SoldTable
from CowBook.Models import Treatment

app = Blueprint('app', __name__, url_prefix='/')


@app.context_processor
def inject_user():
	return dict(user=current_user)


@app.route('/')
def index():
	return render_template("index.html")


@app.route("/user")
@login_required
def user():
	return render_template("security/User.html")


@app.route('/herd')
def herd():
	tableType = request.args.get("type")
	# data =
	types = {
		"all": get_all,
		"active": get_active,
		"inactive": get_inactive,
		"sold": get_sold,
		"dead": get_dead,
	}
	try:
		data = types[tableType]
	except KeyError:
		return render_template("Herd.html", table=CowTable(get_all()))

	if data is not None:
		data = data()
	if tableType == "sold":
		herdTable = SoldTable(data)
	elif tableType == "dead":
		herdTable = DeathTable(data)
	else:
		herdTable = CowTable(data)
	return render_template("Herd.html", table=herdTable, type=tableType)


@app.route('/herd/add', methods=["GET", "POST"])
@login_required
def add_cow():
	form = CowForm()
	if form.validate_on_submit():
		try:
			tempCow = form.save()
		except Exception:
			flash("That name is already taken. Use a different name!")
			return render_template("/Cow/AddCow.html", form=form)
		return redirect(url_for('app.cow', cowId=tempCow.id))
	return render_template("/Cow/AddCow.html", form=form)


@app.route('/herd/duedates')
def view_due_date():
	defaultDate = Treatment.get_next_due_date() or datetime.now()
	return render_template("/Cow/DueDates.html", defaultDate=defaultDate)


@app.route('/herd/<cowId>')
def cow(cowId):
	tempCow = get_by_id(cowId)
	if tempCow is None:
		return render_template('/Error/404.html', content="Cow {} not found".format(cowId))
	dam = get_by_id(tempCow.dam_id)
	sire = get_by_id(tempCow.sire_id)

	calves = CowTable(get_calves(tempCow))
	weights = Treatment.WeightTable(Treatment.get_weights(tempCow))
	events = Treatment.EventTable(Treatment.get_events(tempCow))
	treats = Treatment.TreatmentTable(Treatment.get_treatments(tempCow))
	pregnancyChecks = Treatment.PregnancyCheckTable(Treatment.get_pregnancy_checks(tempCow))
	breedings = Treatment.BredTable(Treatment.get_breedings(tempCow))
	notes = NoteTable(tempCow.notes)

	return render_template("/Cow/Cow.html", cow=tempCow, calves=calves, weights=weights, events=events,
	                       treatments=treats, pregnancyCheck=pregnancyChecks, notes=notes, breedings=breedings, dam=dam,
	                       sire=sire)


@app.route('/herd/<cowId>/stats')
def stats(cowId):
	tempCow = get_by_id(cowId)
	if tempCow is None:
		return render_template('/Error/404.html', content="Cow {} not found".format(cowId))
	return render_template('/Cow/Dashboard.html', cow=tempCow)


def handle_add_event_form(tempCow=None):
	"""Creates and validates a multi use form"""
	# Single form with every possible field
	form = Treatment.Form()
	# Set choices for form type on frontend
	form.formType.choices = [("Event", "Event"), ("Treatment", "Treatment"), ("Weight", "Weight"), ("Sale", "Sale"),
	                         ("Death", "Death")]
	if tempCow is None or tempCow.sex == "cow":
		form.formType.choices.append(("Pregnancy Check", "Pregnancy Check"))
		form.formType.choices.append(("Bred", "Bred"))
	form.formType.choices.sort(key=lambda x: x[0])
	formType = {
		"Event": EventForm,
		"Treatment": TreatmentForm,
		"Weight": WeightForm,
		"Pregnancy Check": PregnancyCheckForm,
		"Bred": BredForm,
		"Sale": SaleForm,
		"Death": DeathForm,
	}
	item = formType.get(form.formType.data)
	if item is None:
		item = form
	else:
		item = item()
	return item


@app.route('/herd/<cowId>/addEvent', methods=["GET", "POST"])
@login_required
def treatment(cowId):
	tempCow = get_by_id(cowId)
	if tempCow is not None:
		item = handle_add_event_form(tempCow)
		if item.validate_on_submit():
			item.save(cowId)
		else:
			if request.method == 'POST':
				item.validate()
			return render_template("/Cow/AddTreatment.html", cow=tempCow, form=item)
		return redirect(url_for('app.cow', cowId=cowId))
	else:
		return render_template("/Error/404.html")


@app.route('/herd/<cowId>/addNote', methods=["GET", "POST"])
@login_required
def add_note(cowId):
	tempCow = get_by_id(cowId)
	if tempCow is not None:
		form = NoteForm()

		if form.validate_on_submit():
			form.save(cowId)
		else:
			if request.method == 'POST':
				form.validate()
			return render_template("/Cow/AddNote.html", cow=tempCow, form=form)
		return redirect(url_for('app.cow', cowId=cowId))
	else:
		return render_template("/Error/404.html", content="Cow not found!")


@app.route('/herd/<cowId>/edit', methods=["GET", "POST"])
@login_required
def edit_cow(cowId):
	tempCow = get_by_id(cowId)
	if tempCow is None:
		return render_template('/Error/404.html', content="Cow {} not found".format(cowId))
	form = EditCowForm(cowId)
	if form.validate_on_submit():
		form.save()
		return redirect(url_for('app.cow', cowId=cowId))
	form.setup()
	return render_template("/Cow/Edit.html", cow=tempCow, form=form)


@app.route('/herd/<cowId>/edit/dam', methods=["GET", "POST"])
@login_required
def edit_dam(cowId):
	newCow = get_by_id(cowId)
	if newCow is None:
		return render_template('/Error/404.html', content="Cow {} not found".format(cowId))
	form = EditParentForm(cowId, parent="dam")
	if form.validate_on_submit():
		try:
			form.save()
		except ValueError as e:
			flash(e)
			return render_template("/Cow/EditParent.html", cow=newCow, form=form)
		return redirect(url_for('app.cow', cowId=cowId))
	return render_template("/Cow/EditParent.html", cow=newCow, form=form)


@app.route('/herd/<cowId>/edit/sire', methods=["GET", "POST"])
@login_required
def edit_sire(cowId):
	newCow = get_by_id(cowId)
	if newCow is None:
		return render_template('/Error/404.html', content="Cow {} not found".format(cowId))
	form = EditParentForm(cowId, parent="sire")
	if form.validate_on_submit():
		try:
			form.save()
		except ValueError as e:
			flash(e)
			return render_template("/Cow/EditParent.html", cow=newCow, form=form)
		return redirect(url_for('app.cow', cowId=cowId))
	return render_template("/Cow/EditParent.html", cow=newCow, form=form)


@app.route('/herd/<cowId>/edit/active/<boolean>', methods=["POST"])
@login_required
def set_active(cowId, boolean):
	newCow = get_by_id(cowId)
	if newCow is None:
		return render_template('/Error/404.html', content="Cow {} not found".format(cowId))
	val = True if boolean == "true" else None
	val = False if boolean == "false" else val
	if val is None:
		return render_template('/Error/404.html',
		                       content='Invalid parameter "{}". Accepted values: true, false'.format(boolean))
	newCow.active = val
	newCow.save()
	flash("{} marked as {}".format(newCow.name, "active" if val else "inactive"))
	return redirect(url_for('app.cow', cowId=cowId))


@app.route('/herd/treatments')
def treatments():
	treatType = request.args.get("type")
	tables = []
	if treatType == "medical":
		tables.append(Treatment.TreatmentTable(Treatment.get_treatments()))
	elif treatType == "weight":
		tables.append(Treatment.WeightTable(Treatment.get_weights()))
	elif treatType == "pregnancyCheck":
		tables.append(Treatment.PregnancyCheckTable(Treatment.get_pregnancy_checks()))
	elif treatType == "breeding":
		tables.append(Treatment.BredTable(Treatment.get_breedings()))
	else:
		treatType = "all"
		tables.append(Treatment.EventTable(Treatment.get_events()))
		tables.append(Treatment.TreatmentTable(Treatment.get_treatments()))
		tables.append(Treatment.WeightTable(Treatment.get_weights()))
		tables.append(Treatment.BredTable(Treatment.get_breedings()))
		tables.append(Treatment.PregnancyCheckTable(Treatment.get_pregnancy_checks()))
	return render_template("Treatments.html", tables=tables, treat=treatType)


@app.route('/herd/treatments/<treatId>/edit', methods=["GET", "POST"])
@login_required
def edit_treatment(treatId):
	treat = Treatment.get_treatment(treatId)
	if treat is None:
		return render_template('/Error/404.html', content="Treatment {} not found".format(treat))
	form = EditTreatmentForm(treatId)
	if form.validate_on_submit():
		try:
			form.save(None)
		except ValueError as e:
			flash(e)
			return render_template("/EditTreatment.html", form=form, treat=treat)
		return redirect(url_for('app.cow', cowId=treat.parent))
	form.setup()
	return render_template("/EditTreatment.html", form=form, treat=treat)


@app.route('/herd/treatments/customform', methods=['GET', 'POST'])
@login_required
def custom_form_treatment():
	form = handle_add_event_form()
	if request.method == 'POST':
		if form.validate():
			kwargs = request.form.copy()
			kwargs['csrf_token'] = None
			kwargs['submit'] = None
			for key, value in request.form.items():
				if value is None or value == "":
					del kwargs[key]
			return redirect(url_for('app.custom_form', **kwargs))

CowBook/templates/Cow/AddCow.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
    Add Cow
{% endblock %}

{% block app_content %}

<div class="formwrapper">
    <form method="POST" enctype="multipart/form-data">
        <h2 class="title">Add Cow</h2><br>
        Name: {{wtf.form_field(form.name, "inline")}}
        DOB: {{wtf.form_field(form.dob, "inline")}}
        Tag #: {{wtf.form_field(form.earTag, "inline")}}
        Sex: {{wtf.form_field(form.sex, "inline")}}
        Carrier: {{form.carrier}}<br><br>
        Owner: {{wtf.form_field(form.owner, "inline")}}
        Markings: {{wtf.form_field(form.markings, "inline")}}
        Photo: {{wtf.form_field(form.photo, "inline")}}
        {{ wtf.form_errors(form, hiddens="only") }}
        {{ form.csrf_token }}
        {{wtf.form_field(form.submit) }}
    </form>
</div>

{% endblock %}

CowBook/templates/Cow/AddNote.html
{% extends "base.html" %}

{% block title %}
Add Note
{% endblock %}

{% block app_content %}
<div id="formwrapper">
    <form method="POST" enctype="multipart/form-data">
        <h2 class="title">Add Note</h2><br>
        Date: {{wtf.form_field(form.date, "inline")}}
        Text:
        <textarea class="form-control" id="text" name="text" required="" rows="3"></textarea>
        {{ wtf.form_errors(form, hiddens="only") }}
        {{ form.csrf_token }}<br>
        <input id="submit" class="btn btn-default" value="submit" type="submit">
    </form>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<script>
    var today = new Date();
    today = today.getFullYear() + "-" + String(today.getMonth() + 1).padStart(2, '0') + "-" + String(today.getDate()).padStart(2, '0');
    document.getElementById("date").value = today;

</script>
{%- endblock scripts %}

CowBook/templates/Cow/AddTreatment.html
{% extends "base.html" %}

{% block title %}
    Add Event
{% endblock %}

{% block app_content %}


<div id="formwrapper">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script>
        function hideForms() {
            var input = $("#formType")[0].value;
            //console.log($("#formType")[0]);
            hideAll();
            switch(input) {
                case "Treatment":
                    show(["#lotNo", "#expiration", "#withdrawal", "#dosage", "#unit"]);
                    break;
                case "Weight":
                    show(["#weight"]);
                    break;
                case "Pregnancy Check":
                    show(["#pregnant"]);
                    break;
                case "Bred":
                    show(["#sire"]);
                    break;
                case "Sale":
                    show(["#weight", "#perPound", "total"]);
                    break;
                case "Death":
                    show(["#cause"]);
                    break;

            }
        }

        function hideAll() {
            var forms = ["#lotNo", "#expiration", "#withdrawal", "#dosage", "#unit", "#pregnant", "#weight", "#sire", "#perPound", "#total", "#cause"];
            for (var i = 0; i < forms.length; ++i) {
                $(forms[i]).parent().css("display", "none");
            }
        }

        function show(list) {
            for (var i = 0; i < list.length; ++i) {
                $(list[i]).parent().css("display", "block");
            }
        }

        $("#formType").change( function() {
            hideForms();
        });
        $(document).ready( function () {
            hideForms();
        });

        function calculateValues() {
            var weight = $("#weight")[0].value;
            var perPound = $("#perPound")[0].value;
            var total = $("#total")[0].value;
            if (weight != "" && perPound != "") {
                $("#total")[0].value = (perPound * weight).toFixed(2);
            } else if (weight != "" && total != "") {
                $("#perPound")[0].value = (total / weight).toFixed(2);
            } else if (total != "" && perPound != "") {
                $("#weight")[0].value = (total/perPound).toFixed(2);
            }
        }

        $("#weight").change( function() {
            var weight = $("#weight")[0].value;
            var perPound = $("#perPound")[0].value;
            var total = $("#total")[0].value;
            if (weight != "") {
                if (perPound != "") {
                    $("#total")[0].value = (perPound * weight).toFixed(2);
                } else if (total != "") {
                    $("#perPound")[0].value = (total / weight).toFixed(2);
                }
            }
        });
        $("#perPound").change( function() {
            var weight = $("#weight")[0].value;
            var perPound = $("#perPound")[0].value;
            var total = $("#total")[0].value;
            if (perPound != "") {
                if (weight != "") {
                    $("#total")[0].value = (perPound * weight).toFixed(2);
                } else if (total != "") {
                    $("#weight")[0].value = (total/perPound).toFixed(2);
                }
            }
        });
        $("#total").change( function() {
            var weight = $("#weight")[0].value;
            var perPound = $("#perPound")[0].value;
            var total = $("#total")[0].value;
            if (total != "") {
                if (weight != "") {
                    $("#perPound")[0].value = (total / weight).toFixed(2);
                } else if (perPound != "") {
                    $("#weight")[0].value = (total/perPound).toFixed(2);
                }
            }
        });
        $("#dosage").on( "input", function() {
            var unit = $("#unit")[0];
            if (unit.value == "" || unit.value == null) {
                unit.value = "ml";
            }
        });
1   </script>
{%- endblock scripts %}

CowBook/templates/Cow/Cow.html
{% extends "base.html" %}

{% block title %}
{{cow.name}}
{% endblock %}

{% block app_content %}
{% if cow.photo %}
<a href="{{'/static/Pictures/' + cow.photo}}">
    <img src="{{'/static/Pictures/small/' + cow.photo}}" height="200" style="float:left; margin-right:10px">
</a>
{% endif %}
{% if current_user.is_authenticated %}
<span style="float: right">
        <ul class="nav navbar-nav">
            <li class="dropdown">
                <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#"
                   role="button">Edit
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">

                    <li><a href="{{url_for('app.treatment', cowId=cow.id)}}" role="button">Add Event</a></li>
                    <li><a href="{{url_for('app.add_note', cowId=cow.id)}}" role="button">Add Note</a></li>
                    <li>
                        <a href="{{ url_for('app.edit_dam', cowId=cow.id)}}">{{"{} Dam".format("Edit" if dam else "Add")}}</a></li>
                    <li><a href="{{ url_for('app.edit_sire', cowId=cow.id)}}">{{"{} Sire".format("Edit" if sire else "Add")}}</a></li>
                    <li><a>
                        <form method="post"
                              action="{{ url_for('app.set_active', cowId=cow.id, boolean='false' if cow.active else 'true')}}"
                              class="inline">
                          <button type="submit" name="submit_param" value="submit_value" class="btn btn-link"
                                  style="padding: unset; text-decoration: none; color: inherit;">
                            Mark {{"Inactive" if cow.active else "Active"}}
                          </button>
                        </form>
                        </a>
                    </li>

                    <li><a href="{{ url_for('app.edit_cow', cowId=cow.id) }}">Edit</a></li>

                </ul>
            </li>
          </ul>

    </li>
    </ul>
    </span>
{% endif %}
<div id="cowInfo">
    <h3>
        Name: {{cow.name}}<br>
        DOB: {{cow.dob.strftime("%m/%d/%Y")}}<br>
        Tag #: {{cow.earTag}}<br>
        Sex: {{cow.sex}}<br>
        Carrier: {{cow.carrier}}<br>
        Owner: {{cow.owner}}<br>
        Markings: {{cow.markings}}<br>
        Status: {{cow.status}}<br>

            {% if dam or sire %}
            Parents:<br>
        </h3>
        <h4>
            {% if dam %}
            Dam: <a href="{{url_for('app.cow', cowId=dam.id)}}">{{dam.name}}</a><br>
            {% endif %}
            {% if sire %}
            Sire: <a href="{{url_for('app.cow', cowId=sire.id)}}">{{sire.name}}</a>
            {% endif %}
        </h4>
            {% else %}
            </h3>
            {% endif %}

    </div>

    <div id="tables">
        {% if cow.sex == "cow" %}
        <h3>Breedings</h3>
            {{breedings}}
        <h3>Pregnancy Checks:</h3>
            {{pregnancyCheck}}
        {% endif %}

        {% if cow.sex != "steer"%}
        <h3>Calves:</h3>
        {{calves}}
        {% endif %}
        <h3>Weights:</h3>
        {{weights}}
        <h3>Events:</h3>
        {{events}}
        <h3>Treatments:</h3>
        {{treatments}}
        <h3>Notes:</h3>
        {{notes}}
        <br>

    </div>
<a class="btn btn-primary" href="{{url_for('app.stats', cowId=cow.id)}}" role="button">Stats</a>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ fancy_table('HerdTable', buttons=False) }}
{{ fancy_table('Weights', buttons=false, hideFirst=True) }}
{{ fancy_table('Events', buttons=false, hideFirst=True) }}
{{ fancy_table('Treatments', buttons=false, hideFirst=True) }}
{{ fancy_table('PregnancyChecks', buttons=false, hideFirst=True) }}
{{ fancy_table('breedingHistory', buttons=false, hideFirst=True) }}
{{ fancy_table('NoteTable', buttons=False) }}
{%- endblock scripts %}

CowBook/templates/Cow/Dashboard.html
{% extends "base.html" %}

{% block title %}
{{cow.name}}'s stats
{% endblock %}

{% block head %}
{{ super() }}
<link href="{{ url_for('static', filename='timeline/css/timeline.min.css') }}" rel="stylesheet">
{% endblock %}

{% block app_content %}
<template id="timelineItem">
    <div class="timeline__item">
        <div class="timeline__content">
            <h2></h2>
            <h3></h3>
            <p></p>
        </div>
    </div>
</template>
Age: {{cow.age}} years<br>
Calves: {{cow.calves|length}}<br><br>
<div class="timeline">
    <div class="timeline__wrap">
        <div class="timeline__items">
        </div>
    </div>
</div>
<br><br>
<div id="lineChart">

</div>

{% endblock %}

{% block scripts %}
{{ super() }}
<script>
    function addTimeLineData(data) {
        var template = $("#timelineItem")[0].content.children[0];
        var body = $(".timeline__items")[0];
        body.textContent = '';
        for (var i = 0; i < data.length; ++i) {
            let clone = template.cloneNode(true);
            let attributes = clone.children[0].children;
            attributes[0].innerText = data[i].date;
            attributes[1].innerText = data[i].type;
            attributes[2].innerText = data[i].notes;
            body.appendChild(clone);
        }
        jQuery('.timeline').timeline({
          mode: 'horizontal',
          forceVerticalMode: 600, // 600px
          startIndex: null
        });
    }

    $.get("/api/herd/{{cow.id}}/treatments", addTimeLineData);

</script>
<script src="{{ url_for('static', filename='timeline/js/timeline.min.js') }}"></script>
<link rel="stylesheet" href="https://uicdn.toast.com/tui.chart/latest/tui-chart.min.css">
<script src="https://uicdn.toast.com/tui.chart/latest/tui-chart-all.min.js"></script>
<script>
var container = document.getElementById('lineChart');
var dob = moment("{{cow.dob}}", 'YYYY/MM/DD');
categories = [dob.format("L")];
data = [0];
var now = moment();

function calculateAge(start, end) {
    return end.diff(start, "years", true);
}

var date = dob.clone();
while (date < now) {
    date.add(1, 'months');
    categories.push(date.format("L"));
    data.push(calculateAge(dob, date));
}

var data = {
    categories: categories,
    series: [
        {
            name: '{{cow.name}}',
            data: data
        }
    ]
};
var options = {
    usageStatistics: false,
    chart: {
        width: document.body.clientWidth/1.25,
        height: 540,
        title: 'Age over time'
    },
    yAxis: {
        title: 'Age (Years)',
    },
    xAxis: {
        title: 'Month',
        pointOnColumn: true,
        dateFormat: 'MMM',
        tickInterval: 'auto'
    },
    series: {
        showDot: false,
        zoomable: true
    },

};
var chart = tui.chart.lineChart(container, data, options);

</script>
{% endblock %}

CowBook/templates/Cow/DueDates.html
{% extends "base.html" %}
{%- block styles %}
{{ super() }}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/core/main.min.css"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/daygrid/main.min.css"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/core/main.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/daygrid/main.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/timegrid/main.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/list/main.min.js"></script>
<script>

  document.addEventListener('DOMContentLoaded', function() {
    var calendarEl = document.getElementById('calendar');

    var calendar = new FullCalendar.Calendar(calendarEl, {
        plugins: [ 'dayGrid', 'timeGrid', 'list' ],
        header: { center: 'dayGridMonth,timeGridWeek' }, // buttons for switching between views
        defaultDate: "{{defaultDate}}",
        views: {
            dayGridMonth: {
                titleFormat: { year: 'numeric', month: '2-digit', day: '2-digit' },
                defaultDate: "{{defaultDate}}"
            },
            list: {
                type: 'list'
            }
        },
        events: "/api/herd/duedates"
    });

    calendar.render();
    //console.log(calendar.view);
  });

</script>
{%- endblock styles %}

{% block title %}
    Due Dates
{% endblock %}
{% block app_content %}
<body>
    <a class="btn btn-primary" href="{{url_for('api.export_due_dates')}}" role="button"
       style="float: right; margin-left: 0.75em">Export</a>
    <div id='calendar'></div>

  </body>
{% endblock %}

CowBook/templates/Cow/Edit.html
{% extends "base.html" %}

{% block app_content %}
    <style>
        #cssfade {
             background-image: url('/static/Assets/uploadphoto.png');
             height: 200px;
             width: 200px;
             background-repeat: no-repeat;
             background-size: cover;
        }
        #cssfade img {
            -webkit-transition: all ease 1s;
            -moz-transition: all ease 1s;
            -o-transition: all ease 1s;
            -ms-transition: all ease 1s;
            transition: all ease 1s;
        }
        #cssfade img:hover {
            opacity: 0;
        }

        .photo > input {
            display: none;
        }

        .photo img {
            cursor: pointer;
        }
    </style>
    <form method="POST" enctype="multipart/form-data">
        <div>
        <div class="photo">
            <label for="photo">
                {% if cow.photo %}
                    <div  id="cssfade">
                        <img id="output" src="{{'/static/Pictures/small/' + cow.photo}}" height="200" style="float:left; margin-right:10px">
                    </div>
                {% else %}
                    <img  id="output" src="/static/Assets/uploadphoto.png" height="200" style="float:left; margin-right:10px">
                {% endif %}
            </label>
            <input id="photo" accept="image/*" name="photo" type="file" onchange="loadFile(event)"/>
        </div>
        <div id="cowInfo">
            <h3>
                Name: {{wtf.form_field(form.name, "inline")}}
                DOB: {{wtf.form_field(form.dob, "inline")}}
                Tag #: {{wtf.form_field(form.earTag, "inline")}}
                Sex: {{wtf.form_field(form.sex, "inline")}}
                Carrier: {{form.carrier}}<br><br>
                Owner: {{wtf.form_field(form.owner, "inline")}}
                Markings: {{wtf.form_field(form.markings, "inline")}}
                {{ wtf.form_errors(form, hiddens="only") }}
            </h3>
        </div>
        </div>
        {{ form.csrf_token }}
        {{wtf.form_field(form.submit) }}
    </form>

	

	
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
    var loadFile = function(event) {
        var image = document.getElementById('output');
        image.src = URL.createObjectURL(event.target.files[0]);
    };
    </script>
{%- endblock scripts %}

CowBook/templates/Cow/EditParent.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block app_content %}

<div class="formwrapper">
    <h2 class="title">Edit {{form.parentType}}</h2>
    <form method="POST">
    <select class="form-control" id="id" name="id">
    </select>
        <input id="submit" class="btn btn-default" name="submit" type="submit" value="Save">
    </form>
</div>

{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        var cow = JSON.parse('{{ cow | tojson | safe }}');
        $.getJSON('/api/{{form.parentType}}s', function(data) {
            let element = $("#id")[0];
            for (var i = 0; i < data.length; i++) {
                if (cow.id != data[i].id)
                    element.append(new Option(data[i].name + " #" + data[i].earTag, data[i].id));
            }
        })
    </script>
{%- endblock scripts %}